### ISSUE TITLE
可以联系您吗？

### ISSUE THREAD

**Issue by llllll128** [wangxr0526/RetroPrime#3]
方便话可以加我的qq729868721交流一下吗，谢谢！

**Comment by wangxr0526** [comment]
抱歉，您的回复现在才看到，我的邮箱是wangxr2018@lzu.edu.cn，欢迎邮件联系。

**Comment by wangxr0526** [comment]
> 方便话可以加我的qq729868721交流一下吗，谢谢！

抱歉，您的回复现在才看到，我的邮箱是wangxr2018@lzu.edu.cn，欢迎邮件联系。
